# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bitcoinaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoinaddress',
            name='text',
        ),
        migrations.AddField(
            model_name='bitcoinaddress',
            name='address',
            field=models.CharField(default=b'test address', max_length=500),
        ),
        migrations.AddField(
            model_name='bitcoinaddress',
            name='priv_key',
            field=models.CharField(default=b'test private key', max_length=500),
        ),
        migrations.AddField(
            model_name='bitcoinaddress',
            name='priv_wif',
            field=models.CharField(default=b'test wif private key', max_length=500),
        ),
    ]
