# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160113_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinaddress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
